# Generated by Django 4.0.3 on 2022-04-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('roles', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('rating_classification', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avg_rating', models.IntegerField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='RunTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'runtime',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('born', models.CharField(max_length=50)),
                ('died', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testProj.movies')),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='run_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testProj.runtime'),
        ),
    ]
